[package]
name = "mathemizer"
version = "0.0.1"
description = "A math package"
authors = ["apinanyogaratnam"]
edition = "2022"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
